# Request to the localhost version
### Get all users (Localhost)
GET http://localhost:3000/api/users
Content-Type: application/json

###

### Get a user by id (Localhost)
GET http://localhost:3000/api/users/:id
Content-Type: application/json


###

# Request to the published (deployed) version
### Get all users (Published)
GET https://cse341-xeh0.onrender.com/api/users
Content-Type: application/json

###

### Get a user by id (Published)
POST https://cse341-xeh0.onrender.com/api/users/:id
Content-Type: application/json

